### ISSUE TITLE
Error: Invalid CAR version: 2

### ISSUE THREAD

**Issue by cryptowhizzard** [web3-storage/ipfs-car#142]
After doing a successful retrieval from a client when unpacking i get an error.

Unpacking with Go-car on the same file works.

npx ipfs-car --list 1674816302356116587.car
Error: Invalid CAR version: 2
  at readHeader (/root/node_modules/@ipld/car/cjs/lib/decoder.js:59:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async decodeIndexerComplete (/root/node_modules/@ipld/car/cjs/lib/indexer.js:37:28)
  at async Function.fromFile (/root/node_modules/@ipld/car/cjs/lib/indexed-reader.js:73:22)
  at async listFilesInCar (/root/node_modules/ipfs-car/dist/cjs/cli/lib.js:11:23)

**Comment by vasco-santos** [comment]
Hi @cryptowhizzard 

We should now support CAR v2 spec. Could you update `ipfs-car` and try again? Let us know if it worked fine now
