### ISSUE TITLE
What steps are required to build this?

### ISSUE THREAD

**Issue by TheDiscordian** [web3-storage/ipfs-car#143]
Heya, I was looking into possibly contributing to this repo as I'm working on similar things, but I can't seem to get it to build. Here's what I tried:

```
git clone git@github.com:web3-storage/ipfs-car.git
cd ipfs-car
npm install
npm run build
```

Everything is smooth sailing up until `npm run build`:

```
disco@MacBook-Air ipfs-car % npm run build

> ipfs-car@0.9.1 build
> npm run compile:esm && npm run compile:cjs


> ipfs-car@0.9.1 compile:esm
> ttsc -p tsconfig.json && echo '{ "type" : "module" }' > dist/esm/package.json

/Users/disco/Programming/ipfs-car/node_modules/ttypescript/lib/loadTypescript.js:29
    var _e = ts.versionMajorMinor.split('.'), major = _e[0], minor = _e[1];
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.loadTypeScript (/Users/disco/Programming/ipfs-car/node_modules/ttypescript/lib/loadTypescript.js:29:35)
    at Object.<anonymous> (/Users/disco/Programming/ipfs-car/node_modules/ttypescript/lib/tsc.js:8:27)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/disco/Programming/ipfs-car/node_modules/ttypescript/bin/tsc:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)

Node.js v19.6.0
```

Should I be doing something differently?

```
disco@MacBook-Air ipfs-car % uname -a
Darwin MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```

**Comment by TheDiscordian** [comment]
Hey, I've updated to fdc46f5b87bc54209bb352f42797471f0db85e3a and see no change when running `npm run build`, no change at all CC @vasco-santos. Is there something special I should be doing to get the build to succeed?
