### ISSUE TITLE
Can't install with node 20.11.1 on Windows

### ISSUE THREAD

**Issue by bruyeret** [web3-storage/ipfs-car#166]
## The issue

When installing this package on Windows, I get an error:
```
$ npm i ipfs-car
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: ...
```

The log doesn't help much. This part is repeated three times:
```
406 verbose stack Error: ENOENT: no such file or directory, lstat
406 verbose stack     at lstat (node:internal/fs/promises:915:32)
406 verbose stack     at C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\bin-links\lib\shim-bin.js:50:14
406 verbose stack     at Array.map (<anonymous>)
406 verbose stack     at shimBin (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\bin-links\lib\shim-bin.js:50:5)
406 verbose stack     at linkBins (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\bin-links\lib\link-bins.js:18:19)
406 verbose stack     at binLinks (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\bin-links\lib\index.js:25:5)
406 verbose stack     at [createBinLinks] (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:419:15)
406 verbose stack     at [linkAllBins] (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:405:42)
406 verbose stack     at [build] (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:193:31)
406 verbose stack     at async Arborist.rebuild (C:\Users\...\AppData\Roaming\nvm\v20.11.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:95:5)
407 verbose cwd C:\dev\TEMP\ipfs-car
408 verbose Windows_NT 10.0.22631
409 verbose node v20.11.1
410 verbose npm  v10.2.4
411 error code ENOENT
412 error syscall lstat
413 error errno -4058
414 error enoent ENOENT: no such file or directory, lstat
415 error enoent This is related to npm not being able to find a file.
415 error enoent
416 verbose exit -4058
```

I use `node v20.11.1` and `npm 10.2.4` on Windows 11.

## To reproduce

```
nvm use 20.11.1
npm i ipfs-car
```

**Comment by bumblefudge** [comment]
fwiw node v18.18.2/npm 10.8.1 worked fine on wsl2 ubuntu on windows 11 over here, as did node 20.15.0/npm 10.7.0 .

**Comment by bumblefudge** [comment]
maybe a transitive dependency fixed itself in the meantime?

**Comment by endomorphosis** [comment]
> maybe a transitive dependency fixed itself in the meantime?

no, the error is still present.
