### ISSUE TITLE
npx error : crypto is not defined

### ISSUE THREAD

**Issue by sliard** [web3-storage/ipfs-car#77]
Hi,

Does command with npx still work ?
I always have this error : 

    npx ipfs-car --pack test.txt --output test.car
    ReferenceError: crypto is not defined
      at Hasher.encode (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/multiformats/cjs/src/hashes/sha2-browser.js:7:56)
      at Hasher.digest (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/multiformats/cjs/src/hashes/hasher.js:16:35)
      at persist (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/ipfs-unixfs-importer/src/utils/persist.js:29:42)
      at /home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/ipfs-unixfs-importer/src/dag-builder/file/buffer-importer.js:47:20
      at /home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/it-parallel-batch/index.js:32:16
      at Array.map (<anonymous>)
      at parallelBatch (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/it-parallel-batch/index.js:27:26)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async buildFileBatch (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/ipfs-unixfs-importer/src/dag-builder/file/index.js:45:20)
      at async batch (/home/me/.npm/_npx/68468/lib/node_modules/ipfs-car/node_modules/it-batch/index.js:20:20)

Thanks for help :) 

Env : 
 - Ubuntu 20.04.2 LTS 
 - npm@6.14.8
 - npx@6.14.8

**Comment by sliard** [comment]
I forgot this one :) 
Node : v12.16.1

**Comment by vasco-santos** [comment]
We only support Node@14+, given 14 is the currently [LTS version of Node](https://nodejs.org/en/about/releases/). So, you will need to update and the problem should be fixed

**Comment by sliard** [comment]
Work fine with v16.7.0 !
Thanks !
