### ISSUE TITLE
fs_1.default.promises.rm is not a function

### ISSUE THREAD

**Issue by parkan** [web3-storage/ipfs-car#94]
Get this error in car packing, the resulting car file seems sane but we need to be able to trust the error status of the command as we'll be running this on 50k+ items in the archive. 

```
parkan@ytterbium:~/archive_org/filecoin/staging$ time ipfs-car --unpack Qmdk4jahNe1gSRWdYS96Jmas9CD6c1Rdp8twSWkErgc6jK.car --output test/

real	0m15.917s
user	0m13.457s
sys	0m7.452s
parkan@ytterbium:~/archive_org/filecoin/staging$ time ipfs-car --pack test --output ipfs-car-out.car
TypeError: fs_1.default.promises.rm is not a function
    at FsBlockStore.close (/usr/lib/node_modules/ipfs-car/dist/cjs/blockstore/fs.js:57:41)
    at Object.packToFs (/usr/lib/node_modules/ipfs-car/dist/cjs/pack/fs.js:27:26)
    at async handleInput (/usr/lib/node_modules/ipfs-car/dist/cjs/cli/cli.js:90:36)

real	0m17.625s
user	0m27.249s
sys	0m15.474s
```

**Comment by parkan** [comment]
node 16 fixes it, hooray! I will naggingly leave this open till the engines directive is added to help future :car: operators
